# image: gitpod/workspace-full:latest
image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    branches: true

tasks:
  - prebuild: gem install travis
    command: |
      ln -s /tmp/gitpod/.vim /home/gitpod/.vim
      ln -s /tmp/gitpod/.vim/vimrc /home/gitpod/.vimrc
      ln -s /tmp/gitpod/.tmux.conf /home/gitpod/.tmux.conf
      alias tmux="tmux -2"

  # - init: |
      # clear
      # printf '\033[31m\033[1mWARNING:\033[0m %s\n' "This is affected by a bug https://github.com/gitpod-io/gitpod/issues/1528, please ignore the blank preview and open the generated website in a browser"
      # printf '\n%s\n' "Press any key to continue.."
      # read -r something
      # # HOTFIX: '-no-localhost' is a hotfix for bug https://github.com/gitpod-io/gitpod/issues/1528
      # firebase login --no-localhost
      # printf '\033[0;34m\033[1mINFO:\033[0m %s\n' "You can now export variable FIREBASE_TOKEN to avoid parsing 'firebase subcommand --token YOUR_TOKEN' for each usage of firebase"
      # printf '\033[0;34m\033[1mINFO:\033[0m %s\n' "The export of FIREBASE_TOKEN variable can be done account-wide and specified per repository on https://gitpod.io/settings/"      
