language: node_js
node_js:
  - "12"
script:
  - cd functions
  - npm install
  - cd ..
after_success:
  - npm install -g firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN" --only functions:addMessage,functions:makeUppercase
